### ISSUE TITLE
Can't compile Juce project with Visual Studio 2015

### ISSUE THREAD

**Issue by xaviergodart** [grame-cncm/faust#23]
Hi there,
First, thank you for your work. I'm enjoying faust a lot on my dsp learning journey.
I'm playing with the new **faust2juce** script. Works great with linux makefile export target.

Now, I'm trying to compile a vst for Windows 64bit with Visual Studio 2015, and I have a bunch of errors. I use the **master-dev** branch. Sorry if it lacks of details, I'm a newbie in C++, especially under Windows.

First, I have syntax errors with _std::max_ and _std::min_ functions. I was able to fix them replacing:

`std::min(0., 1.)`

by:

`(std::min)(0., 1.)`

on all occurrences.

Second, I have errors with the _Rectangle_ class (**"Rectancle" is ambiguous**). I was able to fix them by adding _juce::_ namespace to the class like this:

`juce::Rectangle<int>(0, 0, 640., 480.)`

Third, I have errors with the _FAUSTFLOAT_ type (**"FAUSTFLOAT is undefined"**). Replacing all the occurrences of _FAUSTFLOAT_ by _float_ and removing the definition of the type seems to be ok with the compiler, but I'm unsure it would work at the end.

Finally, I have a last error, which I'm unable to fix: **'_InterlockedDecrement': ambiguous call to overloaded function**.

I'm really not sure if it's a configuration problem on my side, or if it's related to the faust generated juce project.

Thanks for helping!

**Comment by sletz** [comment]
1) can you try again with latest git version (master-dev) ?
2) can you send me the complete error log you get with the cpp file that cause it ?

Thanks.

**Comment by xaviergodart** [comment]
Just updated to the latest git version on master-dev. _Rectangle_ and _FAUSTFLOAT_ errors seem to have disappeared. I still get the other errors. Here is the full debug build output (I have included warnings too).

`
1>------ Rebuild All started: Project: RevF, Configuration: Debug x64 ------
1>  FaustPluginProcessor.cpp
1>  juce_audio_basics.cpp
1>  juce_audio_devices.cpp
1>  juce_audio_formats.cpp
1>  juce_audio_plugin_client_utils.cpp
1>  juce_audio_plugin_client_VST2.cpp
1>  juce_audio_processors.cpp
1>  juce_audio_utils.cpp
1>..\..\FaustPluginProcessor.cpp(17): warning C4100: 'x': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(21): warning C4100: 'x': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(219): warning C4100: 'date_usec': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(427): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(428): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(429): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(436): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(436): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(436): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(436): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(436): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(436): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(437): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(437): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(437): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(437): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(437): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(437): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(438): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(438): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(438): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(438): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(438): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(438): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(442): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(442): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(442): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(442): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(443): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(443): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(443): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(443): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(527): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>..\..\FaustPluginProcessor.cpp(529): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>..\..\FaustPluginProcessor.cpp(938): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(939): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(940): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(945): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(945): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(946): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(946): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(947): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(947): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(947): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(947): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(947): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(947): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(948): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(948): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(948): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(948): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(948): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(948): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(949): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(949): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(949): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(949): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(949): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(949): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(953): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(953): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(953): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(953): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(954): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(954): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(954): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(954): warning C4100: 'label': unreferenced formal parameter
1>  juce_core.cpp
1>..\..\FaustPluginProcessor.cpp(1193): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1195): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1197): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1203): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1207): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1211): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1211): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1211): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1211): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1211): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1215): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1215): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1215): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1215): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1215): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1219): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1219): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1219): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1219): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1219): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1225): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1225): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1225): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1229): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1229): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1229): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1235): warning C4100: 'val': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1235): warning C4100: 'key': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1235): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1274): error C2589: '(': illegal token on right side of '::'
1>..\..\FaustPluginProcessor.cpp(1274): error C2059: syntax error: '::'
1>..\..\FaustPluginProcessor.cpp(1596): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2361): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2363): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2365): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2367): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2369): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2371): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2611): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2746): error C2589: '(': illegal token on right side of '::'
1>..\..\FaustPluginProcessor.cpp(2746): error C2059: syntax error: '::'
1>..\..\FaustPluginProcessor.cpp(2857): error C2589: '(': illegal token on right side of '::'
1>..\..\FaustPluginProcessor.cpp(2857): error C2059: syntax error: '::'
1>..\..\FaustPluginProcessor.cpp(2857): error C2612: trailing ')' illegal in base/member initializer list
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(8): warning C4079: unexpected token 'string' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(8): warning C4081: expected 'newline'; found ')' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(9): warning C4081: expected 'constant'; found 'string' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(13): warning C4081: expected ')'; found 'string' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(669): warning C4161: #pragma pack(pop...): more pops than pushes (compiling source file ..\..\FaustPluginProcessor.cpp)
1>..\..\FaustPluginProcessor.cpp(11299): fatal error C1004: unexpected end-of-file found
1>  juce_data_structures.cpp
1>  juce_events.cpp
1>  juce_graphics.cpp
1>  juce_gui_basics.cpp
1>  juce_gui_extra.cpp
1>  juce_opengl.cpp
1>  juce_osc.cpp
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
`

**Comment by sletz** [comment]
Can you send me the FaustPluginProcessor.cpp file that you are compiling ?

**Comment by sletz** [comment]
std::min, std::max rewritten for better compatibility, can you try master-dev again?

**Comment by xaviergodart** [comment]
I just made a very simple gain control dsp to test that. Here is the generated cpp: https://gist.github.com/xaviergodart/66e3b7ac9483735bb8ec1bba82ec923b

I still have a couple of errors with the last master-dev:
```
1>------ Rebuild All started: Project: gainCtl, Configuration: Debug x64 ------
1>  FaustPluginProcessor.cpp
1>  juce_audio_basics.cpp
1>  juce_audio_devices.cpp
1>  juce_audio_formats.cpp
1>  juce_audio_plugin_client_utils.cpp
1>  juce_audio_plugin_client_VST2.cpp
1>  juce_audio_processors.cpp
1>  juce_audio_utils.cpp
1>..\..\FaustPluginProcessor.cpp(206): warning C4100: 'date_usec': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(414): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(415): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(416): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(423): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(423): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(423): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(423): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(423): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(423): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(424): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(424): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(424): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(424): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(424): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(424): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(425): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(425): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(425): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(425): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(425): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(425): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(429): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(429): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(429): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(429): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(430): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(430): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(430): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(430): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(514): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>..\..\FaustPluginProcessor.cpp(516): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>..\..\FaustPluginProcessor.cpp(925): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(926): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(927): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(932): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(932): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(933): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(933): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(934): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(934): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(934): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(934): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(934): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(934): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(935): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(935): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(935): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(935): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(935): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(935): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(936): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(936): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(936): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(936): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(936): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(936): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(940): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(940): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(940): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(940): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(941): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(941): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(941): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(941): warning C4100: 'label': unreferenced formal parameter
1>  juce_core.cpp
1>..\..\FaustPluginProcessor.cpp(1180): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1182): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1184): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1190): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1194): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1198): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1198): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1198): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1198): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1198): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1202): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1202): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1202): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1202): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1202): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1206): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1206): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1206): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1206): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1206): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1212): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1212): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1212): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1216): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1216): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1216): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1222): warning C4100: 'val': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1222): warning C4100: 'key': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1222): warning C4100: 'zone': unreferenced formal parameter
1>  juce_data_structures.cpp
1>..\..\FaustPluginProcessor.cpp(1527): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1527): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1527): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1527): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1532): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1532): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1532): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1532): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1537): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1537): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1537): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1537): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1544): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1544): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1549): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1549): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1556): warning C4100: 'val': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1556): warning C4100: 'key': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1556): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(1583): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2348): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2350): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2352): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2354): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2356): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2358): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2598): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(2979): warning C4100: 'fmid': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(2987): warning C4100: 'fmid': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3014): warning C4100: 'fmid': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3022): warning C4100: 'fmid': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3050): warning C4100: 'v': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'amax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'amid': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'amin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3052): warning C4100: 'curve': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3053): warning C4100: 'amax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3053): warning C4100: 'amid': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3053): warning C4100: 'amin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3057): warning C4100: 'on_off': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3079): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3115): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3434): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3436): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3570): warning C4100: 'comp': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3629): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3702): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3776): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3792): warning C4100: 'button': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(3840): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3842): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3845): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3897): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(3944): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4014): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4094): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4168): warning C4244: '-=': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4171): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4174): warning C4244: '-=': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4190): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4207): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4210): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4315): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4332): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4335): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4413): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4434): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4438): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4537): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4543): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4577): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4575): warning C4100: 'vert': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(4726): warning C4457: declaration of 'comp' hides function parameter
1>  ..\..\FaustPluginProcessor.cpp(4723): note: see declaration of 'comp'
1>..\..\FaustPluginProcessor.cpp(4723): warning C4100: 'comp': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(4882): warning C4457: declaration of 'comp' hides function parameter
1>  ..\..\FaustPluginProcessor.cpp(4876): note: see declaration of 'comp'
1>..\..\FaustPluginProcessor.cpp(4876): warning C4100: 'comp': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(4914): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4918): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4982): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(5002): warning C4244: 'argument': conversion from 'unsigned __int64' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(4987): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5009): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5027): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(5062): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5120): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(5128): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(5225): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5541): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5546): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5567): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5572): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5577): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5598): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5603): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5610): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5725): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5736): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5737): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5738): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5741): warning C4100: 'velocity': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5741): warning C4100: 'pitch': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5741): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5742): warning C4100: 'velocity': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5742): warning C4100: 'pitch': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5742): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5743): warning C4100: 'press': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5743): warning C4100: 'pitch': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5743): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5744): warning C4100: 'press': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5744): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5745): warning C4100: 'value': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5745): warning C4100: 'ctrl': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5745): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5746): warning C4100: 'value': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5746): warning C4100: 'ctrl': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5746): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5747): warning C4100: 'wheel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5747): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5748): warning C4100: 'pgm': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5748): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(5848): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6034): warning C4100: 'v': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6119): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6139): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6165): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6191): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6223): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6255): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6346): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6350): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6355): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6355): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6355): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6359): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6359): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6359): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6363): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6363): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6363): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6370): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6374): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6381): warning C4100: 'zone': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6392): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6388): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6388): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6402): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6398): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6398): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6411): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6407): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6407): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6416): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6416): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6428): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6425): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6425): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6436): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6432): warning C4100: 'pitch': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6432): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6432): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6441): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6441): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6450): warning C4100: 'value': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6450): warning C4100: 'ctrl': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6450): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6450): warning C4100: 'date': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6526): warning C4127: conditional expression is constant
1>..\..\FaustPluginProcessor.cpp(6541): warning C4127: conditional expression is constant
1>..\..\FaustPluginProcessor.cpp(6547): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(6554): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6555): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6556): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6556): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6556): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6556): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6556): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6557): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6557): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6557): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6557): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6557): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6558): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6558): warning C4100: 'max': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6558): warning C4100: 'min': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6558): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(6558): warning C4100: 'label': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7584): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(7796): warning C4100: 'samplingRate': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7797): warning C4100: 'samplingRate': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7806): warning C4100: 'outputs': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7806): warning C4100: 'inputs': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7806): warning C4100: 'count': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7807): warning C4100: 'outputs': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7807): warning C4100: 'inputs': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7807): warning C4100: 'count': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7807): warning C4100: 'date_usec': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7908): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7908): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7908): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7908): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7912): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7912): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7912): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7912): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7916): warning C4100: 'step': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7916): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7916): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7916): warning C4100: 'init': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7922): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7922): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7926): warning C4100: 'fmax': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7926): warning C4100: 'fmin': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(7976): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(7985): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
1>..\..\FaustPluginProcessor.cpp(8339): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>..\..\FaustPluginProcessor.cpp(8372): warning C4100: 'date_usec': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8394): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8405): warning C4100: 'velocity': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8405): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8417): warning C4100: 'wheel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8417): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8420): warning C4100: 'value': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8420): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8427): warning C4100: 'pgm': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8427): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8430): warning C4100: 'press': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8430): warning C4100: 'pitch': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8430): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8433): warning C4100: 'press': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8433): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8436): warning C4100: 'value': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8436): warning C4100: 'ctrl': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8436): warning C4100: 'channel': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8745): warning C4100: 'samplingFreq': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(8785): warning C4457: declaration of 'count' hides function parameter
1>  ..\..\FaustPluginProcessor.cpp(8776): note: see declaration of 'count'
1>..\..\FaustPluginProcessor.cpp(9148): warning C4100: 'arg': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(9148): warning C4100: 'val': unreferenced formal parameter
1>..\..\FaustPluginProcessor.cpp(9161): error C2589: '(': illegal token on right side of '::'
1>..\..\FaustPluginProcessor.cpp(9161): error C2059: syntax error: '::'
1>..\..\FaustPluginProcessor.cpp(9164): error C2589: '(': illegal token on right side of '::'
1>..\..\FaustPluginProcessor.cpp(9164): error C2059: syntax error: '::'
1>..\..\FaustPluginProcessor.cpp(9165): error C2589: '(': illegal token on right side of '::'
1>..\..\FaustPluginProcessor.cpp(9347): error C2872: 'Rectangle': ambiguous symbol
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_graphics\geometry/juce_Rectangle.h(37): note: could be 'juce::Rectangle' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\wingdi.h(4385): note: or       '`anonymous-namespace'::BOOL `anonymous-namespace'::Rectangle(`anonymous-namespace'::HDC,int,int,int,int)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  juce_events.cpp
1>  juce_graphics.cpp
1>  juce_gui_basics.cpp
1>  juce_gui_extra.cpp
1>  juce_opengl.cpp
1>  juce_osc.cpp
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
````

When I fix these errors by hand, I have a new one but it seems related to Juce:

```
1>c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(260): error C2668: '_InterlockedDecrement': ambiguous call to overloaded function (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\intrin.h(209): note: could be 'long _InterlockedDecrement(volatile long *)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8875): note: or       'unsigned __int64 `anonymous-namespace'::_InterlockedDecrement(volatile unsigned __int64 *)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8864): note: or       'unsigned long `anonymous-namespace'::_InterlockedDecrement(volatile unsigned long *)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(8855): note: or       'unsigned int `anonymous-namespace'::_InterlockedDecrement(volatile unsigned int *)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(2706): note: or       '`anonymous-namespace'::LONG `anonymous-namespace'::_InterlockedDecrement(volatile `anonymous-namespace'::LONG *)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(260): note: while trying to match the argument list '(volatile long *)' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(259): note: while compiling class template member function 'int juce::WindowsInterlockedHelpersBase<Type,4>::dec(volatile Type *) noexcept'
1>          with
1>          [
1>              Type=int
1>          ] (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(381): note: see reference to function template instantiation 'int juce::WindowsInterlockedHelpersBase<Type,4>::dec(volatile Type *) noexcept' being compiled
1>          with
1>          [
1>              Type=int
1>          ] (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(305): note: see reference to class template instantiation 'juce::WindowsInterlockedHelpersBase<Type,4>' being compiled
1>          with
1>          [
1>              Type=int
1>          ] (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(322): note: see reference to class template instantiation 'juce::WindowsInterlockedHelpers<Type>' being compiled
1>          with
1>          [
1>              Type=int
1>          ] (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_Atomic.h(317): note: while compiling class template member function 'int juce::Atomic<int>::get(void) noexcept const' (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_ReferenceCountedObject.h(103): note: see reference to function template instantiation 'int juce::Atomic<int>::get(void) noexcept const' being compiled (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_LeakedObjectDetector.h(101): note: see reference to class template instantiation 'juce::Atomic<int>' being compiled (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_LeakedObjectDetector.h(88): note: see reference to class template instantiation 'juce::LeakedObjectDetector<OwnerClass>::LeakCounter' being compiled (compiling source file ..\..\FaustPluginProcessor.cpp)
1>  c:\users\xavier\documents\juce\juce-grapefruit-windows\juce\modules\juce_core\memory/juce_LeakedObjectDetector.h(114): note: see reference to class template instantiation 'juce::LeakedObjectDetector<OwnerClass>' being compiled (compiling source file ..\..\FaustPluginProcessor.cpp)
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by sletz** [comment]
Thanks
Another commit to fix the problems we can fix. Are you testing on JUCE git ? If not you should try with develop branch here : https://github.com/julianstorer/JUCE/tree/develop hoping the _InterlockedDecrement is fixed there. Otherwise please report the issue on JUCE forum : https://forum.juce.com

**Comment by xaviergodart** [comment]
I no longer have any error on the faust generated file. Still have the _InterlockedDecrement error, even with the develop branch of JUCE. I'll report that on their forum as you suggested.
Thank you very much!

**Comment by xaviergodart** [comment]
I reopen this issue because I'm unsure the _InterlockedDecrement error comes from JUCE.
I created an issue on the JUCE github: https://github.com/julianstorer/JUCE/issues/163

It looks like JUCE doesn't like the way the faust generated cpp file includes the winbase.h file, which is included by the windows.h file. I tried changing the order of these inclusions, or remove some of them without getting it to work.

**Comment by xaviergodart** [comment]
It has been fixed. Discussion here : https://github.com/julianstorer/JUCE/issues/163
