### ISSUE TITLE
Checks for llvm versions break on minor version update of llvm

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#573]
Hi! When building faust 2.30.5 I used llvm 11.0.0.
After an upgrade to llvm 11.1.0 a (re)build breaks, because some files rely on overly explicit preprocessor macros: https://github.com/grame-cncm/faust/search?q=LLVM_110

llvm 11.1.0 exposes `LLVM_111` instead of `LLVM_110` and the build breaks.
Maybe this can be somehow improved by relying on "greater than" comparison or by utilizing the `LLVM_VERSION`, which exposes the complete version string?

**Comment by sletz** [comment]
This has been fixed in https://github.com/grame-cncm/faust/commit/5fbe04232cfcf28b3aa6e64a6dd4d9347f3735a8

**Comment by dvzrv** [comment]
I don't think so. The above search link still shows e.g. the remaining explicit matches against `LLVM_110` (but not `LLVM_111`).

**Comment by sletz** [comment]
Build on macOS gives this kind of log: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCPP_BUILD -DCSHARP_BUILD -DC_BUILD -DDLANG_BUILD -DFIR_BUILD -DINTERP_BUILD -DJAVA_BUILD -DLIBDIR=\"lib\" -DLLVM_110 -DLLVM_BUILD -DLLVM_VERSION=\"11.1.0\" -DOCPP_BUILD -DRUST_BUILD -DSOUL_BUILD -DWASM_BUILD `

**Comment by dvzrv** [comment]
Hm, looking at our [build script for llvm](https://github.com/archlinux/svntogit-packages/blob/945f44cad0ce91b2698b4598fd50b6654b275b5e/trunk/PKGBUILD), I don't see anything that would suggest our distribution build deliberately choosing `LLVM_111` over `LLVM_110`.

Given that macports applies [many more patches than us](https://github.com/macports/macports-ports/commit/b5da398cc4194cc4ca5d14c9fb01d48544b582cf), it's more likely that exposing `LLVM_110` when using llvm 11.1.0 is a bug (but I am not an llvm expert ;-) ).

Besides that, do you think that there's a way of doing conditional checks against the version string in the remaining locations, that do not rely on `LLVM_*`?

**Comment by sletz** [comment]
> Hm, looking at our [build script for llvm](https://github.com/archlinux/svntogit-packages/blob/945f44cad0ce91b2698b4598fd50b6654b275b5e/trunk/PKGBUILD), I don't see anything that would suggest our distribution build deliberately choosing `LLVM_111` over `LLVM_110`.
> 
> Given that macports applies [many more patches than us](https://github.com/macports/macports-ports/commit/b5da398cc4194cc4ca5d14c9fb01d48544b582cf), it's more likely that exposing `LLVM_110` when using llvm 11.1.0 is a bug (but I am not an llvm expert ;-) ).
> 
> Besides that, do you think that there's a way of doing conditional checks against the version string in the remaining locations, that do not rely on `LLVM_*`?

What do you mean?

**Comment by dvzrv** [comment]
To do what is described in the initial ticket text and not rely on `LLVM_*` (https://github.com/grame-cncm/faust/search?q=LLVM_110) but to make use of `LLVM_VERSION` instead.

**Comment by dvzrv** [comment]
@sletz argh, nevermind. I just now realized what that change you mentioned actually does! :roll_eyes: 

Nevermind the noise!
